name: Format Code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Create Pull Request
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout -B prettier-formatting origin/main

          if ! git diff --exit-code --quiet ;
          then
            git add .
            git commit -m "style: format code with prettier"
            git push --force origin prettier-formatting

            gh pr create --title "Format code with prettier" --body "Automated code formatting." --base main --head prettier-formatting
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
